config/routes.rb
Rails.application.routes.draw do
  resources :recipes
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"

  Rails.application.routes.draw do
    resources :recipes, only: [:index, :show, :create, :update, :destroy]
    match '*path', to: 'application#route_not_found', via: :all
  end

end


# rails g scaffold Recipe id:integer title:string making_time:string serves:string ingredients:string cost:integer created_at:datetime updated_at:datetime

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/recipe.rb
class Recipe < ApplicationRecord
    validates :title, :making_time, :serves, :ingredients, :cost, presence: true
end

app/models/test.rb
class Test < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :null_session

    def route_not_found
        render json: { message: "No Route matches" }, status: :not_found
      end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :set_recipe, only: [:show, :update, :destroy]

  # GET /recipes or /recipes.json
  def index
    @recipes = Recipe.all
    render json: {
      recipes: @recipes
    }
  end

  # GET /recipes/1 or /recipes/1.json
  def show
        render json: {
          'message': "Recipe details by id",
          'recipe': [@recipe]
        }
  end

  # POST /recipes or /recipes.json
  def create
    @recipe = Recipe.new(recipe_params)

    if @recipe.valid? && @recipe.save
      render json: {
        message: 'Recipe successfully created!',
        recipe: [@recipe]
      }, status: :ok
    else
      render json: {
        message: "Recipe creation failed!",
        required: "title, making_time, serves, ingredients, cost"
        }, status: :ok
    end
    
  end

  # PATCH/PUT /recipes/1 or /recipes/1.json
  def update
    if @recipe.update(recipe_params)
      render json: { message: "Recipe successfully updated!", recipe: [@recipe] }
    else
      render json: { message: "Recipe update failed!", required: "title, making_time, serves, ingredients, cost" }, status: :not_found
    end
  end

  # DELETE /recipes/1 or /recipes/1.json
  def destroy
    @recipe.destroy
    render json: { message: "Recipe successfully removed!" }
  rescue ActiveRecord::RecordNotFound
    render json: { message: "No Recipe found" }, status: :ok
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_recipe
      @recipe = Recipe.find(params[:id])
    rescue ActiveRecord::RecordNotFound
      render json: { message: "No Recipe found" }, status: :not_found
    end

    # Only allow a list of trusted parameters through.
    def recipe_params
      params.permit(:title, :making_time, :serves, :ingredients, :cost)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ApiSample</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/recipes/_form.html.erb
<%= form_with(model: recipe) do |form| %>
  <% if recipe.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(recipe.errors.count, "error") %> prohibited this recipe from being saved:</h2>

      <ul>
        <% recipe.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :id, style: "display: block" %>
    <%= form.number_field :id %>
  </div>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :making_time, style: "display: block" %>
    <%= form.text_field :making_time %>
  </div>

  <div>
    <%= form.label :serves, style: "display: block" %>
    <%= form.text_field :serves %>
  </div>

  <div>
    <%= form.label :ingredients, style: "display: block" %>
    <%= form.text_field :ingredients %>
  </div>

  <div>
    <%= form.label :cost, style: "display: block" %>
    <%= form.number_field :cost %>
  </div>

  <div>
    <%= form.label :created_at, style: "display: block" %>
    <%= form.datetime_field :created_at %>
  </div>

  <div>
    <%= form.label :updated_at, style: "display: block" %>
    <%= form.datetime_field :updated_at %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/recipes/_recipe.html.erb
<div id="<%= dom_id recipe %>">
  <p>
    <strong>Id:</strong>
    <%= recipe.id %>
  </p>

  <p>
    <strong>Title:</strong>
    <%= recipe.title %>
  </p>

  <p>
    <strong>Making time:</strong>
    <%= recipe.making_time %>
  </p>

  <p>
    <strong>Serves:</strong>
    <%= recipe.serves %>
  </p>

  <p>
    <strong>Ingredients:</strong>
    <%= recipe.ingredients %>
  </p>

  <p>
    <strong>Cost:</strong>
    <%= recipe.cost %>
  </p>

  <p>
    <strong>Created at:</strong>
    <%= recipe.created_at %>
  </p>

  <p>
    <strong>Updated at:</strong>
    <%= recipe.updated_at %>
  </p>

</div>

app/views/recipes/edit.html.erb
<h1>Editing recipe</h1>

<%= render "form", recipe: @recipe %>

<br>

<div>
  <%= link_to "Show this recipe", @recipe %> |
  <%= link_to "Back to recipes", recipes_path %>
</div>

app/views/recipes/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Recipes</h1>

<div id="recipes">
  <% @recipes.each do |recipe| %>
    <%= render recipe %>
    <p>
      <%= link_to "Show this recipe", recipe %>
    </p>
  <% end %>
</div>

<%= link_to "New recipe", new_recipe_path %>

app/views/recipes/new.html.erb
<h1>New recipe</h1>

<%= render "form", recipe: @recipe %>

<br>

<div>
  <%= link_to "Back to recipes", recipes_path %>
</div>

app/views/recipes/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @recipe %>

<div>
  <%= link_to "Edit this recipe", edit_recipe_path(@recipe) %> |
  <%= link_to "Back to recipes", recipes_path %>

  <%= button_to "Destroy this recipe", @recipe, method: :delete %>
</div>